// Code generated by "stringer -type ReplaceOrder"; DO NOT EDIT.

package resources

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReplaceAnyOrder-0]
	_ = x[ReplaceCreateFirst-1]
	_ = x[ReplaceDeleteFirst-2]
}

const _ReplaceOrder_name = "ReplaceAnyOrderReplaceCreateFirstReplaceDeleteFirst"

var _ReplaceOrder_index = [...]uint8{0, 15, 33, 51}

func (i ReplaceOrder) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ReplaceOrder_index)-1 {
		return "ReplaceOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplaceOrder_name[_ReplaceOrder_index[idx]:_ReplaceOrder_index[idx+1]]
}
