// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package azure_vault

import (
	"context"
	"fmt"
	"os"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys"
	"github.com/opentofu/opentofu/internal/backend/remote-state/assure/auth"
	"github.com/opentofu/opentofu/internal/encryption/keyprovider"
)

type keyManagementClientInit func(vaultURL string, credential azcore.TokenCredential) (keyManagementClient, error)

// Can be overridden for test mocking
var newKeyManagementClient keyManagementClientInit = func(vaultURL string, credential azcore.TokenCredential) (keyManagementClient, error) {
	return azkeys.NewClient(vaultURL, credential, nil)
}

type authMethodGetter func(authConfig *auth.Config) (auth.AuthMethod, error)

// This can also be overridden for test mocking
var getAuthMethod authMethodGetter = func(authConfig *auth.Config) (auth.AuthMethod, error) {
	return auth.GetAuthMethod(authConfig)
}

// Config
// TODO should I use pointer types, so that I can better determin nil fields?
type Config struct {
	DisableCLI bool `hcl:"disable_cli,optional"`

	ClientID     string `hcl:"client_id,optional"`
	ClientSecret string `hcl:"client_secret,optional"`

	ClientCertPassword string `hcl:"client_certificate_password,optional"`
	ClientCertPath     string `hcl:"client_certificate_path,optional"`

	UseOIDC          bool   `hcl:"use_oidc,optional"`
	OIDCToken        string `hcl:"oidc_token,optional"`
	OIDCTokenPath    string `hcl:"oidc_token_file_path,optional"`
	OIDCRequestURL   string `hcl:"oidc_request_url,optional"`
	OIDCRequestToken string `hcl:"oidc_request_token,optional"`

	UseMSI bool `hcl:"use_msi,optional"`

	MetadataHost   string `hcl:"metadata_host,optional"`
	Environment    string `hcl:"environment,optional"`
	SubscriptionID string `hcl:"subscription_id,optional"`
	TenantID       string `hcl:"tenant_id,optional"`

	// Vault is the key vault URI, of the format "https://myvaultname.vault.azure.net/"
	Vault     string `hcl:"az_vault_uri"`
	KeyName   string `hcl:"az_vault_key_name"`
	KeyLength int    `hcl:"key_length"`

	// Symmetric indicates whether the given key provided is a symmetric encryption key or assymmetric.
	// By default this is false, since any key generated by Azure is always asymmetric; you have to
	// upload a key in order for it to be symmetric.
	// TODO enable and test
	// Symmetric bool `hcl:"symmetric,optional"`
}

func stringAttrEnvFallback(val string, envs ...string) string {
	return stringAttrDefaultEnvFallback(val, "", envs...)
}

func stringAttrDefaultEnvFallback(val, def string, envs ...string) string {
	if val != "" {
		return val
	}
	for _, env := range envs {
		if envVal, ok := os.LookupEnv(env); ok {
			return envVal
		}
	}
	return def
}

func (c Config) Build() (keyprovider.KeyProvider, keyprovider.KeyMeta, error) {
	// This mirrors the azurerm remote state backend, minus storage-specific auth
	ctx := context.Background()

	// TODO when we add Symmetric as a config parameter, use that to determine the algorithm set
	algo := azkeys.EncryptionAlgorithmRSAOAEP256

	if c.KeyName == "" {
		return nil, nil, &keyprovider.ErrInvalidConfiguration{Message: "az_vault_key_name must be provided"}
	}

	if c.Vault == "" {
		return nil, nil, &keyprovider.ErrInvalidConfiguration{Message: "az_vault_uri must be provided"}
	}

	if c.KeyLength < 1 {
		return nil, nil, &keyprovider.ErrInvalidConfiguration{Message: "key_length must be at least 1"}
	}
	if c.KeyLength > 1024 {
		return nil, nil, &keyprovider.ErrInvalidConfiguration{Message: "key_length must be less than the GCP limit of 1024"}
	}

	authConfig := &auth.Config{
		AzureCLIAuthConfig: &auth.AzureCLIAuthConfig{
			CLIAuthDisabled: c.DisableCLI,
		},
		ClientBasicAuthConfig: &auth.ClientBasicAuthConfig{
			ClientID:     stringAttrEnvFallback(c.ClientID, "ARM_CLIENT_ID"),
			ClientSecret: stringAttrEnvFallback(c.ClientSecret, "ARM_CLIENT_SECRET"),
		},
		ClientCertificateAuthConfig: &auth.ClientCertificateAuthConfig{
			ClientCertificatePassword: stringAttrEnvFallback(c.ClientCertPassword, "ARM_CLIENT_CERTIFICATE_PASSWORD"),
			ClientCertificatePath:     stringAttrEnvFallback(c.ClientCertPath, "ARM_CLIENT_CERTIFICATE_PATH"),
		},
		OIDCAuthConfig: &auth.OIDCAuthConfig{
			UseOIDC:           c.UseOIDC,
			OIDCToken:         stringAttrEnvFallback(c.OIDCToken, "ARM_OIDC_TOKEN"),
			OIDCTokenFilePath: stringAttrEnvFallback(c.OIDCTokenPath, "ARM_OIDC_TOKEN_FILE_PATH"),
			OIDCRequestURL:    stringAttrEnvFallback(c.OIDCRequestURL, "ARM_OIDC_REQUEST_URL", "ACTIONS_ID_TOKEN_REQUEST_URL"),
			OIDCRequestToken:  stringAttrEnvFallback(c.OIDCRequestToken, "ARM_OIDC_REQUEST_TOKEN", "ACTIONS_ID_TOKEN_REQUEST_TOKEN"),
		},
		MSIAuthConfig: &auth.MSIAuthConfig{
			UseMsi: c.UseMSI,
		},
		StorageAddresses: &auth.StorageAddresses{
			Environment:    stringAttrDefaultEnvFallback(c.OIDCToken, "public", "ARM_ENVIRONMENT"),
			MetadataHost:   stringAttrEnvFallback(c.OIDCToken, "ARM_METADATA_HOST"),
			SubscriptionID: stringAttrEnvFallback(c.OIDCToken, "ARM_SUBSCRIPTION_ID"),
			TenantID:       stringAttrEnvFallback(c.OIDCToken, "ARM_TENANT_ID"),
		},
	}

	authMethod, err := getAuthMethod(authConfig)
	if err != nil {
		return nil, nil, fmt.Errorf("problem getting an auth method: %w", err)
	}

	authCred, err := authMethod.Construct(ctx, authConfig)
	if err != nil {
		return nil, nil, fmt.Errorf("problem getting auth creds: %w", err)
	}

	client, err := newKeyManagementClient(c.Vault, authCred)
	if err != nil {
		return nil, nil, fmt.Errorf("problem making vault client: %w", err)
	}

	return &keyProvider{
		svc:       client,
		ctx:       ctx,
		keyName:   c.KeyName,
		keyLength: c.KeyLength,
		algo:      algo,
	}, new(keyMeta), nil
}
