// Code generated by "stringer -type=ShowTargetType"; DO NOT EDIT.

package arguments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShowUnknownType-0]
	_ = x[ShowState-1]
	_ = x[ShowPlan-2]
	_ = x[ShowConfig-3]
	_ = x[ShowModule-4]
}

const _ShowTargetType_name = "ShowUnknownTypeShowStateShowPlanShowConfigShowModule"

var _ShowTargetType_index = [...]uint8{0, 15, 24, 32, 42, 52}

func (i ShowTargetType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ShowTargetType_index)-1 {
		return "ShowTargetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ShowTargetType_name[_ShowTargetType_index[idx]:_ShowTargetType_index[idx+1]]
}
