// Code generated by "stringer -type=ShowTargetType"; DO NOT EDIT.

package arguments

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShowUnknownType-0]
	_ = x[ShowState-1]
	_ = x[ShowPlan-2]
	_ = x[ShowConfig-3]
}

const _ShowTargetType_name = "ShowUnknownTypeShowStateShowPlanShowConfig"

var _ShowTargetType_index = [...]uint8{0, 15, 24, 32, 42}

func (i ShowTargetType) String() string {
	if i < 0 || i >= ShowTargetType(len(_ShowTargetType_index)-1) {
		return "ShowTargetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ShowTargetType_name[_ShowTargetType_index[i]:_ShowTargetType_index[i+1]]
}
