# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2

project_name: ghoten

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make protobuf

builds:
  - env:
      - CGO_ENABLED=0

    main: ./cmd/tofu
    binary: ghoten

    flags:
      - "-mod=readonly"
      - "-trimpath"

    ldflags:
      - "-s -w"
      - "-X 'github.com/opentofu/opentofu/version.dev=no'"
      - "-X 'github.com/opentofu/opentofu/version.rawVersion={{.Version}}'"

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: solaris
        goarch: "386"
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm

archives:
  - formats: [tar.gz]
    id: targz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

  - formats: [zip]
    id: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

dockers_v2:
  - id: full
    dockerfile: Dockerfile
    images:
      - "ghcr.io/vmvarela/ghoten"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "{{ .Major }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
      - linux/386
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.vendor": "Ghoten"
      "org.opencontainers.image.description": "Ghoten {{ .Version }}"
      "org.opencontainers.image.url": "https://github.com/vmvarela/opentofu"
      "org.opencontainers.image.documentation": "https://github.com/vmvarela/opentofu/blob/main/README.md"
      "org.opencontainers.image.source": "https://github.com/vmvarela/opentofu"
      "org.opencontainers.image.licenses": "MPL-2.0"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"

  - id: minimal
    dockerfile: Dockerfile.minimal
    images:
      - "ghcr.io/vmvarela/ghoten"
    tags:
      - "{{ .Version }}-minimal"
      - "{{ .Major }}.{{ .Minor }}-minimal"
      - "{{ .Major }}-minimal"
      - "minimal"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
      - linux/386
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}-minimal"
      "org.opencontainers.image.vendor": "Ghoten"
      "org.opencontainers.image.description": "Ghoten {{ .Version }} (minimal)"
      "org.opencontainers.image.url": "https://github.com/vmvarela/opentofu"
      "org.opencontainers.image.documentation": "https://github.com/vmvarela/opentofu/blob/main/README.md"
      "org.opencontainers.image.source": "https://github.com/vmvarela/opentofu"
      "org.opencontainers.image.licenses": "MPL-2.0"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: all
    id: cosign
    cmd: cosign
    certificate: "${artifact}.pem"
    args: ["sign-blob", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-certificate=${certificate}", "--output-signature=${signature}", "${artifact}", "--yes"]

docker_signs:
  - args: ["sign", "--oidc-issuer=https://token.actions.githubusercontent.com", "${artifact}@${digest}", "--yes"]

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  use: github-native

release:
  prerelease: auto
  draft: true
