# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

FROM scratch

LABEL maintainer="Ghoten <https://github.com/vmvarela/opentofu>"

ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/ghoten /usr/local/bin/ghoten

ENTRYPOINT ["/usr/local/bin/ghoten"]
