// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package planning

import (
	"context"
	"fmt"
	"iter"
	"log"

	"github.com/zclconf/go-cty/cty"

	"github.com/opentofu/opentofu/internal/addrs"
	"github.com/opentofu/opentofu/internal/engine/plugins"
	"github.com/opentofu/opentofu/internal/lang/eval"
	"github.com/opentofu/opentofu/internal/lang/exprs"
	"github.com/opentofu/opentofu/internal/lang/grapheval"
	"github.com/opentofu/opentofu/internal/plans"
	"github.com/opentofu/opentofu/internal/states"
	"github.com/opentofu/opentofu/internal/tfdiags"
)

// destroyPlan is the planning implementation for [plans.DestroyMode], dealing
// with the special situation of planning to destroy everything that exists
// in the prior state despite the fact that there are probably some ephemeral
// objects (provider instances, for example) referring to existing objects.
//
// It's tempting to think of "destroy mode" as being equivalent to just removing
// all of the resource instances from the configuration, but that's not quite
// true because destroy mode needs to deal with the unique situation of allowing
// ephemeral objects like provider instances to refer to the prior state of
// objects that are being destroyed, whereas in normal mode that's impossible
// since the resource instances would already have been removed from the
// configuration.
//
// This mode therefore takes quite a different strategy than normal mode where
// we rely on the prior state (after refreshing) as the "result value" for
// each managed resource instance.
func destroyPlan(ctx context.Context, opts *PlanOpts, prevRoundState *states.State, configInst *eval.ConfigInstance, providers plugins.Providers) (*plans.Plan, tfdiags.Diagnostics) {
	var diags tfdiags.Diagnostics
	var closeConfiguredProviders func(ctx context.Context) tfdiags.Diagnostics

	planCtx := newPlanContext(configInst.EvalContext(), prevRoundState, providers, opts)

	// This configInst.DrivePlanning call blocks until the evaluator has
	// visited all expressions in the configuration and calls
	// [planContext.PlanDesiredResourceInstance] on the [planGlue] object for
	// each resource instance it discovers so that we can produce a planned
	// action and result value for each one.
	//
	// It also calls the various "Plan*Orphans" methods at different levels
	// of granularity once it's determined the full set of objects under
	// a given prefix, which planGlue uses to notice when there are
	// prevRoundState resource instances that are no longer in the desired
	// state and so plan to delete or forget them.
	//
	// If this completes without returning any error diagnostics then
	// planCtx.resourceInstObjs should accurately represent the relationships
	// between all of the "current" resource instance objects we found, but
	// we won't discover any deposed objects until the next step below.
	evalResult, moreDiags := configInst.DrivePlanning(ctx, func(oracle *eval.PlanningOracle) eval.PlanGlue {
		closeConfiguredProviders = oracle.Close
		return &planGlueDestroy{
			normalGlue: planGlue{
				planCtx: planCtx,
				oracle:  oracle,
			},
		}
	})
	diags = diags.Append(moreDiags)
	if moreDiags.HasErrors() {
		// If we encountered errors during the eval-based phase then we'll halt
		// here but we'll still produce a best-effort [plans.Plan] describing
		// the situation because that often gives useful information for debugging
		// what caused the errors.
		intermediate, moreDiags := planCtx.Close(ctx)
		diags = diags.Append(moreDiags)
		intermediate.Destroying = true
		plan, moreDiags := finalizePlan(ctx, intermediate, providers)
		diags = diags.Append(moreDiags)
		plan.Errored = true
		return plan, diags
	}
	if evalResult == nil {
		// This should not happen: we should always have an evalResult if
		// there weren't any errors.
		panic(fmt.Sprintf("%T.DrivePlanning returned nil result without any error diagnostics", configInst))
	}

	// We also need to deal with any "deposed" resource instances that were
	// in the previous round state. We do this separately afterwards because
	// these have no direct representation in the configuration at all and
	// so are not in scope for the config eval system. It's also relatively
	// rare for a previous round state to include deposed instances, since it
	// can happen only if the "delete" leg of a create-before-destroy replace
	// failed in the previous round.
	//
	// The provider instance manager should've planned ahead and arranged for
	// any providers we need for these to still be open, waiting for the
	// completion reports generated by our planning calls in this loop.
	//
	// After we complete this work, planCtx.resourceInstObjs is expanded to
	// also include any deposed resource instance objects we discovered.
	ctx = grapheval.ContextWithNewWorker(ctx)
	dpg := evalResult.Glue.(*planGlueDestroy)
	pg := &dpg.normalGlue
	for _, moduleState := range prevRoundState.Modules {
		for _, resourceState := range moduleState.Resources {
			for instKey, instState := range resourceState.Instances {
				instAddr := resourceState.Addr.Instance(instKey)
				for dk := range instState.Deposed {
					// We currently have a schism where we do all of the
					// discovery work using the traditional state model but
					// we then switch to using our new-style "full" object model
					// to act on what we've discovered. This is hopefully just
					// a temporary situation while we're operating in a mixed
					// world where most of the system doesn't know about the
					// new runtime yet.
					objState := prevRoundState.SyncWrapper().ResourceInstanceObjectFull(instAddr.Object(dk))
					if objState == nil {
						// If we get here then there's a bug in the
						// ResourceInstanceObjectFull function, because we
						// should only be here if instAddr and dk correspond.
						// to an actual deposed object.
						panic(fmt.Sprintf("state has %s deposed object %q, but ResourceInstanceObjectFull didn't return it", instAddr, dk))
					}
					diags = diags.Append(
						pg.planDeposedResourceInstanceObject(ctx, instAddr, dk, objState),
					)
				}
			}
		}
	}

	// TODO: Consider factoring most of the work we've done here into a single
	// function that directly returns the "intermediate" object. Exposing
	// planCtx as a mutable object in this function doesn't seem necessary
	// anymore since we only actually care about the results from Close here.
	intermediate, moreDiags := planCtx.Close(ctx)
	diags = diags.Append(moreDiags)
	intermediate.Destroying = true
	plan, moreDiags := finalizePlan(ctx, intermediate, providers)
	diags = diags.Append(moreDiags)
	moreDiags = closeConfiguredProviders(ctx)
	diags = diags.Append(moreDiags)
	if diags.HasErrors() {
		plan.Errored = true
	}
	return plan, diags
}

// planGlueDestroy is a special variant of [eval.PlanGlue] that models the
// very unusual behavior of the "destroy" planning mode, where we pretend that
// nothing is desired and just plan to destroy everything.
//
// This is a wrapper around [planGlue] so it can share some of its logic for
// planning "orphan" resource instances, but returns quite different answers
// to requests from the evaluator.
type planGlueDestroy struct {
	normalGlue planGlue
}

var _ eval.PlanGlue = (*planGlueDestroy)(nil)

// PlanDesiredResourceInstance implements [eval.PlanGlue].
func (p *planGlueDestroy) PlanDesiredResourceInstance(ctx context.Context, inst *eval.DesiredResourceInstance) (cty.Value, tfdiags.Diagnostics) {
	var diags tfdiags.Diagnostics
	log.Printf("[TRACE] planGlueDestroy.PlanDesiredResourceInstance for %s", inst.Addr)

	// In destroy mode we ignore the evaluator's opinion about what is
	// "desired", handing everything in the various orphan-planning functions
	// instead because in destroy mode absolutely nothing is "desired".
	//
	// But we do still need to produce an upgraded-and-refreshed version of
	// the requested resource instance from the prior state so that the
	// evaluator can use that result for any references to this resource
	// instance that might appear in the configuration for ephemeral objects
	// such as provider instances.

	// FIXME: The behavior that follows is focused on managed resource
	// instances. We need to figure out what we ought to do with data resource
	// instances: just rely on their previous run state here too, or to try
	// to read them?
	// Relying on previous run state is risky because there's no mechanism for
	// "upgrading" the data for a data resource type -- the protocol assumes
	// that we'll be re-reading them from scratch every time anyway.
	// But trying to read them here is also risky because that would force the
	// provider instances they use to be configured as a side-effect, which
	// may then rely on state prior state results for managed resources and
	// so cause a schism where we're relying on a mix of stale and updated
	// values. Also, we'd need to decide what happens if the data resource
	// instance isn't readable during the planning phase.
	// There isn't really any great answer here, but we should study the old
	// runtime's handling of this situation and mimic it as closely as we can
	// for backward-compatibility.

	// FIXME: Ideally we'd use [resources.ManagedResourceType] here to match
	// how [planGlue.planDesiredManagedResourceInstance] gets schema, but
	// we want to avoid starting up a "configured" provider here just to fetch
	// the schema, since that would increase the risk of this failing due
	// to the provider config referring to something that isn't available in
	// this weird destroy mode.
	schema, moreDiags := p.normalGlue.planCtx.providers.ResourceTypeSchema(ctx, inst.Provider, inst.ResourceMode, inst.ResourceType)
	diags = diags.Append(moreDiags)
	if moreDiags.HasErrors() {
		return exprs.AsEvalError(cty.DynamicVal), diags
	}

	prevState := p.normalGlue.planCtx.prevRoundState.SyncWrapper().ResourceInstanceObjectFull(inst.Addr.CurrentObject())
	if prevState == nil {
		// If this is something that didn't exist at all in the prior state
		// then we have nothing reasonable to return here, so we'll return
		// a completely-unknown value.
		//
		// In practice this can only occur in the unusual situation where
		// someone adds both a resource block and an ephemeral object config
		// (e.g. a provider block) referring to it and then immediately runs
		// a destroy-mode plan without first applying the change to create the
		// managed resources, which is not a supported usage pattern. Returning
		// unknown in that case makes this behave the same as what happens in
		// normal mode when a provider configuration depends on an unknown value
		// from a resource instance that hasn't been created yet: the provider
		// gets sent an unknown value in its configuration and gets to decide
		// for itself how it wants to handle that situation, including possibly
		// making our subsequent calls to PlanResourceChange signal that the
		// provider needs to defer planning that change.
		return cty.UnknownVal(schema.Block.ImpliedType()), diags
	}

	// TODO: The refreshing and upgrading logic is currently embedded in the
	// middle of [planGlue.planDesiredManagedResourceInstance] and not callable
	// separately. Furthermore, in destroy planning mode we need to upgrade
	// and refresh both in here _and_ in the various "orphan" functions below
	// because both codepaths need the latest version of each object, but we'd
	// prefer not to perform those steps twice so we'd need to arrange for
	// each distinct resource instance object to only be upgraded and refreshed
	// once. For now we're just not upgrading or refreshing here at all because
	// we want to let the main code settle a little more before we start
	// factoring out parts of it, but this does mean that upgrading to a new
	// version of a provider immediately before destroying anything, or
	// destroying when there's drift in the remote system that OpenTofu doesn't
	// know about yet, will misbehave for now..
	//
	// Idea for later: perhaps we can build a separate "state refresh manager"
	// that is initialized with the previous run state and can then be asked
	// for the upgraded-and-refreshed state for specific resource instance
	// objects. It would then memoize the results keyed by resource instance
	// object address so that if asked again for the same object it can just
	// immediately return that result, and thus we would upgrade and refresh
	// each object at most once. (That could also be a nice place to encapsulate
	// the updates to old-style state models that we currently do so that we
	// can return a plan shaped roughly like what the old runtime shims are
	// expecting, instead of doing it inline in the main planning function.)
	upgradedState := prevState
	refreshedState := upgradedState

	obj, err := states.DecodeResourceInstanceObjectFull(refreshedState, schema.Block.ImpliedType())
	if err != nil {
		diags = diags.Append(tfdiags.AttributeValue(
			tfdiags.Error,
			"Invalid prior state for resource instance",
			fmt.Sprintf(
				"Cannot decode the most recent state snapshot for %s: %s.\n\nIs the selected version of %s incompatible with the provider that most recently changed this object?",
				inst.Addr, tfdiags.FormatError(err), inst.Provider,
			),
			nil, // this error belongs to the whole resource config
		))
		return cty.UnknownVal(schema.Block.ImpliedType()), diags
	}

	// TODO: Do we need to add any dependency-related marks to this? We're
	// primarily relying on state-based dependencies in destroy mode, but maybe
	// we need to add marks here too so that dependencies can propagate through
	// ephemeral objects that would still be working in terms of configuration.
	return obj.Value, diags
}

// PlanModuleCallOrphans implements [eval.PlanGlue].
func (p *planGlueDestroy) PlanModuleCallOrphans(ctx context.Context, callerModuleInstAddr addrs.ModuleInstance, desiredCalls iter.Seq[addrs.ModuleCall]) tfdiags.Diagnostics {
	// The evaluator is designed to call different Plan*Orphans methods for
	// each container it finds so that it can report which individual objects
	// are desired and so we could in theory then plan deletion only of the
	// ones that are not desired.
	// However, in destroy mode the evaluator's opinions about what is desired
	// are irrelevant and ignored. We just handle the entire process in one
	// call when we're asked to plan orphan module calls in the root module,
	// since we know that call will happen exactly once and we don't need any
	// of the unique information passed as arguments to the other functions.
	if !callerModuleInstAddr.IsRoot() {
		return nil // we only respond when asked about the root module instance
	}

	// Using resourceInstancesFilter here is a little silly since we're
	// intentionally visiting everything, but it's convenient to reuse its
	// deep state tree walk and keep this a similar shape to the other
	// orphan-planning functions in [planGlue].
	orphaned := resourceInstancesFilter(p.normalGlue.planCtx.prevRoundState, func(_ addrs.AbsResourceInstance) bool {
		return true
	})
	var diags tfdiags.Diagnostics
	for addr, state := range orphaned {
		diags = diags.Append(
			p.normalGlue.planOrphanResourceInstance(ctx, addr, state),
		)
	}
	return diags
}

// PlanModuleCallInstanceOrphans implements [eval.PlanGlue].
func (p *planGlueDestroy) PlanModuleCallInstanceOrphans(ctx context.Context, moduleCallAddr addrs.AbsModuleCall, desiredInstances iter.Seq[addrs.InstanceKey]) tfdiags.Diagnostics {
	// In this implementation, planGlueDestroy.PlanModuleCallOrphans does all of the work
	return nil
}

// PlanResourceInstanceOrphans implements [eval.PlanGlue].
func (p *planGlueDestroy) PlanResourceInstanceOrphans(ctx context.Context, resourceAddr addrs.AbsResource, desiredInstances iter.Seq[addrs.InstanceKey]) tfdiags.Diagnostics {
	// In this implementation, planGlueDestroy.PlanModuleCallOrphans does all of the work
	return nil
}

// PlanResourceOrphans implements [eval.PlanGlue].
func (p *planGlueDestroy) PlanResourceOrphans(ctx context.Context, moduleInstAddr addrs.ModuleInstance, desiredResources iter.Seq[addrs.Resource]) tfdiags.Diagnostics {
	// In this implementation, planGlueDestroy.PlanModuleCallOrphans does all of the work
	return nil
}
