// Code generated by "stringer -type=resourceInstanceReplaceOrder -trimprefix=replace"; DO NOT EDIT.

package planning

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[replaceAnyOrder-0]
	_ = x[replaceCreateThenDestroy-1]
	_ = x[replaceDestroyThenCreate-2]
}

const _resourceInstanceReplaceOrder_name = "AnyOrderCreateThenDestroyDestroyThenCreate"

var _resourceInstanceReplaceOrder_index = [...]uint8{0, 8, 25, 42}

func (i resourceInstanceReplaceOrder) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_resourceInstanceReplaceOrder_index)-1 {
		return "resourceInstanceReplaceOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _resourceInstanceReplaceOrder_name[_resourceInstanceReplaceOrder_index[idx]:_resourceInstanceReplaceOrder_index[idx+1]]
}
