// Code generated by "stringer -type=SeverityLevel -linecomment"; DO NOT EDIT.

package tfdiags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorLevel-69]
	_ = x[WarningLevel-87]
}

const (
	_SeverityLevel_name_0 = "Error"
	_SeverityLevel_name_1 = "Warning"
)

func (i SeverityLevel) String() string {
	switch {
	case i == 69:
		return _SeverityLevel_name_0
	case i == 87:
		return _SeverityLevel_name_1
	default:
		return "SeverityLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
