// Code generated by "stringer -type=opCode"; DO NOT EDIT.

package execgraph

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opResourceInstanceCurrentMeta-1]
	_ = x[opResourceInstanceDesired-2]
	_ = x[opResourceInstancePrior-3]
	_ = x[opManagedFinalPlan-4]
	_ = x[opManagedApply-5]
	_ = x[opManagedPrepareDepose-6]
	_ = x[opManagedPerformDepose-7]
	_ = x[opManagedDesposedMeta-8]
	_ = x[opManagedAlreadyDeposed-9]
	_ = x[opManagedChangeAddr-10]
	_ = x[opDataRead-11]
}

const _opCode_name = "opResourceInstanceCurrentMetaopResourceInstanceDesiredopResourceInstancePrioropManagedFinalPlanopManagedApplyopManagedPrepareDeposeopManagedPerformDeposeopManagedDesposedMetaopManagedAlreadyDeposedopManagedChangeAddropDataRead"

var _opCode_index = [...]uint8{0, 29, 54, 77, 95, 109, 131, 153, 174, 197, 216, 226}

func (i opCode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_opCode_index)-1 {
		return "opCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opCode_name[_opCode_index[idx]:_opCode_index[idx+1]]
}
