// Code generated by "stringer -type=opCode"; DO NOT EDIT.

package execgraph

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opResourceInstanceDesired-1]
	_ = x[opResourceInstancePrior-2]
	_ = x[opManagedFinalPlan-3]
	_ = x[opManagedApply-4]
	_ = x[opManagedPrepareDepose-5]
	_ = x[opManagedPerformDepose-6]
	_ = x[opManagedAlreadyDeposed-7]
	_ = x[opManagedChangeAddr-8]
	_ = x[opDataRead-9]
}

const _opCode_name = "opResourceInstanceDesiredopResourceInstancePrioropManagedFinalPlanopManagedApplyopManagedPrepareDeposeopManagedPerformDeposeopManagedAlreadyDeposedopManagedChangeAddropDataRead"

var _opCode_index = [...]uint8{0, 25, 48, 66, 80, 102, 124, 147, 166, 176}

func (i opCode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_opCode_index)-1 {
		return "opCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opCode_name[_opCode_index[idx]:_opCode_index[idx+1]]
}
