# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This RFC has been inspired by the Rust RFC template https://github.com/rust-lang/rfcs/blob/master/0000-template.md

name: Submit RFC
description: Submit a highly-structured change request for public discussion.
labels: ["rfc", "pending-decision"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an RFC!
        
        RFCs are a highly-structured format for submitting change requests. All major changes to OpenTofu should first go through an RFC, to have a place for the community to discuss.
        
        The template has a lot of fields and is inspired by the Rust RFC template. Please take your time to fill it out carefully.
        
        Working experimental PoCs in a draft Pull Request are a very welcome attachment to an RFC, especially ones that are easy to check out and take for a spin.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        One paragraph explanation of the feature.
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: |
        Why are we doing this? What problem are we solving?
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: user-facing-description
    attributes:
      label: User-facing description
      description: |
        Please describe in detail how the feature would work from the perspective of somebody using:
          - How can the feature be used?
          - How would you explain the feature to somebody?
          - Please provide examples of the feature in action.

      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: technical-description
    attributes:
      label: Technical Description
      description: |
        Please describe in detail how the feature would work from a technical perspective:
          - Which components of OpenTofu would be involved in the change?
          - How would the components need to change?
          - Are there any interactions with other features that should be mentioned?
          - Are the any edge cases of the feature that should be discussed?
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: rationale-and-alternatives
    attributes:
      label: Rationale and alternatives
      description: |
        - What would be the impact of this feature?
        - Why is this solution better than alternative solutions to this problem, if there are any?
        - How would the OpenTofu user experience suffer if we didn't do this.
      placeholder:
      value:
    validations:
      required: true

  - type: textarea
    id: downsides
    attributes:
      label: Downsides
      description: |
        - Are there any disadvantages of implementing this?
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: unresolved-questions
    attributes:
      label: Unresolved Questions
      description: |
        - Are there any specific parts of the feature you're not sure about?
        - Are there any specific parts of the technical implementation you're not sure about?
        - Are there any other questions or unknowns that need to be answered before implementing this?
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: |
        - Please post any issues or RFCs related to this one.
      placeholder:
      value:
    validations:
      required: false

  - type: textarea
    id: poc-pull-request
    attributes:
      label: Proof of Concept
      description: |
        - If there is a Pull Request with a Proof of Concept, please link it here.
        - Please concisely describe how to take the PoC for a spin.
      placeholder:
      value:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled and you have filled out all required fields, please check that you did not forget a **Title** for the issue.
