// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package views

import (
	"github.com/opentofu/opentofu/internal/addrs"
	"github.com/opentofu/opentofu/internal/command/arguments"
	"github.com/opentofu/opentofu/internal/lang/marks"
	"github.com/opentofu/opentofu/internal/tfdiags"
)

// Used to track duplicate diagnostic entries in DeprecationDiagnosticAllowed()
type DeprecationDiagnosticAllowedSeen map[any]any

// DeprecationDiagnosticAllowed is used to determine if a diagnostic generated by a deprecation check against an
// output or a variable should be allowed to be shown to the user based on the given DeprecationWarningLevel.
// This is making use of tfdiags.Diagnostic#ExtraInfo() to figure out if the diagnostic is generated by a deprecation check.
func (v *View) DeprecationDiagnosticAllowed(diagnostic tfdiags.Diagnostic, seen DeprecationDiagnosticAllowedSeen) bool {
	outputCause, outputOk := marks.DiagnosticDeprecationCause(diagnostic)

	if !outputOk {
		// If it's not a deprecation warning diagnostic, always allow it to not filter out diagnostics unrelated with deprecation
		return true
	}

	// Check for dupes
	if outputOk {
		if _, outputSeen := seen[outputCause]; outputSeen {
			// Already processed
			return false
		}
		seen[outputCause] = outputCause
	}

	switch v.ModuleDeprecationWarnLvl {
	case arguments.DeprecationWarningLevelAll:
		return true
	case arguments.DeprecationWarningLevelLocal:
		switch {
		case outputOk: // do not allow deprecation warnings for outputs from remote module calls
			if outputCause.Module == "" {
				return true // Root module
			}
			mod, modDiags := addrs.ParseModuleStr(outputCause.Module)
			if modDiags.HasErrors() {
				// TODO log
				return true
			}
			return !v.isRemoteModuleSource(mod) // do not allow deprecation warnings for outputs from remote module calls
		}
	case arguments.DeprecationWarningLevelNone:
		return false
	}
	// unreachable
	return true
}
