// Code generated by "stringer -type=ResourceMode -output=resource_mode_string.go resource_mode.go"; DO NOT EDIT.

package tofu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ManagedResourceMode-0]
	_ = x[DataResourceMode-1]
}

const _ResourceMode_name = "ManagedResourceModeDataResourceMode"

var _ResourceMode_index = [...]uint8{0, 19, 35}

func (i ResourceMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResourceMode_index)-1 {
		return "ResourceMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceMode_name[_ResourceMode_index[idx]:_ResourceMode_index[idx+1]]
}
