// Code generated by "stringer -type=DeferralReason"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeferredReasonUnknown-0]
	_ = x[DeferredBecauseResourceConfigUnknown-1]
	_ = x[DeferredBecauseProviderConfigUnknown-2]
	_ = x[DeferredBecausePrereqAbsent-3]
}

const _DeferralReason_name = "DeferredReasonUnknownDeferredBecauseResourceConfigUnknownDeferredBecauseProviderConfigUnknownDeferredBecausePrereqAbsent"

var _DeferralReason_index = [...]uint8{0, 21, 57, 93, 120}

func (i DeferralReason) String() string {
	if i < 0 || i >= DeferralReason(len(_DeferralReason_index)-1) {
		return "DeferralReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeferralReason_name[_DeferralReason_index[i]:_DeferralReason_index[i+1]]
}
