// Code generated by "stringer -type=DeprecationWarningLevel deprecation_level.go"; DO NOT EDIT.

package tofu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeprecationWarningLevelAll-0]
	_ = x[DeprecationWarningLevelLocal-1]
	_ = x[DeprecationWarningLevelNone-2]
}

const _DeprecationWarningLevel_name = "DeprecationWarningLevelAllDeprecationWarningLevelLocalDeprecationWarningLevelNone"

var _DeprecationWarningLevel_index = [...]uint8{0, 26, 54, 81}

func (i DeprecationWarningLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeprecationWarningLevel_index)-1 {
		return "DeprecationWarningLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeprecationWarningLevel_name[_DeprecationWarningLevel_index[idx]:_DeprecationWarningLevel_index[idx+1]]
}
