// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package command

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/opentofu/opentofu/internal/command/workdir"
)

// More thorough tests for providers mirror can be found in the e2etest
func TestProvidersMirror(t *testing.T) {
	// noop example
	t.Run("noop", func(t *testing.T) {
		view, done := testView(t)

		meta := Meta{
			WorkingDir: workdir.NewDir("."),
			View:       view,
		}
		code := RunCommander(t, ProvidersMirrorCommander(), meta, []string{"."})
		output := done(t)
		if code != 0 {
			t.Fatalf("wrong exit code. expected 0, got %d\ngot output:\n%s", code, output.All())
		}
	})

	t.Run("missing arg error", func(t *testing.T) {
		view, done := testView(t)

		meta := Meta{
			WorkingDir: workdir.NewDir("."),
			View:       view,
		}
		code := RunCommander(t, ProvidersMirrorCommander(), meta, []string{"-no-color"})
		output := done(t)
		if code != RunResultHelp {
			t.Fatalf("wrong exit code. expected 1, got %d", code)
		}

		got := output.Stderr()
		if !strings.Contains(got, "The providers mirror command requires an output directory") {
			t.Fatalf("missing directory error from output, got:\n%s\n", got)
		}
	})

	// TestProvidersMirrorUseMirrorCredentials verifies that the JSON index files
	// generated by "tofu providers mirror" include "use_mirror_credentials": true
	// for each archive entry, so that consumers using the mirror as a network mirror
	// will automatically get credential forwarding (related to issue #4314).
	t.Run("use_mirror_credentials in generated JSON", func(t *testing.T) {
		// Setting up a temporary working directory with no provider requirements so
		// the command doesn't attempt any network downloads.
		workDir := t.TempDir()
		if err := os.WriteFile(filepath.Join(workDir, "main.tf"), []byte(""), 0644); err != nil {
			t.Fatalf("failed to create empty main.tf: %s", err)
		}

		// Setting up an output directory pre-populated with a dummy zip file placed
		// at the correct path layout that SearchLocalDirectory expects:
		//   <outputDir>/<hostname>/<namespace>/<type>/terraform-provider-<type>_<version>_<os>_<arch>.zip
		outputDir := t.TempDir()
		archiveDir := filepath.Join(outputDir, "registry.opentofu.org", "hashicorp", "null")
		if err := os.MkdirAll(archiveDir, 0755); err != nil {
			t.Fatalf("failed to create archive directory: %s", err)
		}
		// Write a minimal but valid-enough file so Hash() doesn't error.
		zipPath := filepath.Join(archiveDir, "terraform-provider-null_2.1.0_linux_amd64.zip")
		if err := os.WriteFile(zipPath, []byte("PK\x05\x06"+strings.Repeat("\x00", 18)), 0644); err != nil {
			t.Fatalf("failed to create dummy zip: %s", err)
		}

		view, done := testView(t)
		meta := Meta{
			WorkingDir: workdir.NewDir(workDir),
			View:       view,
		}
		code := RunCommander(t, ProvidersMirrorCommander(), meta, []string{outputDir})
		output := done(t)
		if code != 0 {
			t.Fatalf("wrong exit code. expected 0, got %d\ngot output:\n%s", code, output.All())
		}

		// The version-specific JSON index (e.g. "2.1.0.json") should contain
		// "use_mirror_credentials": true for every archive entry.
		versionIndexPath := filepath.Join(archiveDir, "2.1.0.json")
		data, err := os.ReadFile(versionIndexPath)
		if err != nil {
			t.Fatalf("failed to read generated version index %s: %s", versionIndexPath, err)
		}

		var versionIndex struct {
			Archives map[string]map[string]json.RawMessage `json:"archives"`
		}
		if err := json.Unmarshal(data, &versionIndex); err != nil {
			t.Fatalf("failed to parse generated version index JSON: %s\ncontent: %s", err, data)
		}

		for platform, archiveMeta := range versionIndex.Archives {
			rawCreds, ok := archiveMeta["use_mirror_credentials"]
			if !ok {
				t.Errorf("generated JSON for platform %q is missing use_mirror_credentials field", platform)
				continue
			}
			var useMirrorCreds bool
			if err := json.Unmarshal(rawCreds, &useMirrorCreds); err != nil {
				t.Errorf("platform %q: use_mirror_credentials is not a boolean: %s", platform, rawCreds)
				continue
			}
			if !useMirrorCreds {
				t.Errorf("platform %q: expected use_mirror_credentials to be true, got false", platform)
			}
		}

		if len(versionIndex.Archives) == 0 {
			t.Errorf("expected at least one archive entry in generated version index, got none\ncontent: %s", data)
		}
	})
}
