name: Post-release

on:
  workflow_dispatch:
  release:
    types: [created, published, edited, prereleased, released]

jobs:
  redeploy:
    runs-on: ubuntu-latest
    name: Redeploy Cloudflare Worker
    permissions: {}
    steps:
      - name: Redeploy get.opentofu.org
        run: curl -fsS -X POST "${{ secrets.GET_OPENTOFU_DEPLOY_HOOK }}"
