name: Pull Request Opened
permissions:
  pull-requests: write

# only trigger on pull request closed events
on:
  pull_request_target:
    types: [ opened ]

jobs:
  pr_open_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Reminder for the PR assignee: If this is a user-visible change, please update the changelog as part of the PR."
            })
